version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    env_file:
      - ./mysql.env
    networks:
      - custom
  web:
    build: .
    networks:
      - custom
    ports:
      - "127.111.111.111:80:8080"
    env_file:
      - ./web.env
    depends_on:
      - mysql

networks:
  custom:
